# Generated by Django 4.2.5 on 2023-09-10 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_date_created_post_date_alter_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='id_user',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='id_user',
        ),
    ]
